sudo: true

env:
  global:
    - BRANCH=stable
    - QUIET=1
    - UML_FIG=0
    - UML_DOCKERCOMPOSE=1

install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - docker-compose run test