static:
  build: static
  command: bundle exec middleman server --force-polling --verbose --latency=2 --port=4567
  ports:
    - "4567:4567"
  volumes:
    - ${PWD}/static/middleman:/home/app

api:
  build: api
  command: rackup -p 80
  ports:
    - "3000:80"
  volumes:
    - ${PWD}/api:/home/app