static:
  build: static
  command: bundle exec middleman server --force-polling --verbose --latency=2 --port=80
  links: 
    - api
  ports:
    - "3002:80"
  volumes:
    - ${PWD}/static/middleman:/home/app


test:
  build: test
  command: guard -p
  links: 
    - mongo
  volumes:
    - ${PWD}/test/Gemfile:/home/app/Gemfile
    - ${PWD}/test/Gemfile.lock:/home/app/Gemfile.lock
    - ${PWD}/test/Guardfile:/home/app/Guardfile
    - ${PWD}/static/middleman/source:/home/app/source
    - ${PWD}/api:/home/app/api
    - ${PWD}/test/middleman/config:/home/app/config
    - ${PWD}/test/middleman/features:/home/app/features
    - ${PWD}/test/middleman/lib:/home/app/lib
    - ${PWD}/test/middleman/config.rb:/home/app/config.rb
    - ${PWD}/test/.rspec:/home/app/.rspec

api:
  build: api
  command: rackup -p 80
  links:
    - mongo
  ports:
    - "3000:80"
  volumes:
    - ${PWD}/api:/home/app

cms:
  build: cms
  command:  bundle exec rackup -p 80 -o 0.0.0.0
  environment:
    - SECRET_KEY_BASE=as2387sd2370sd210128sd8023
  ports:
    - "3001:80"
  links:
    - mongo
  volumes:
    - ${PWD}/cms:/home/app

mongo:
  image: mongo
  ports:
    - "27017:27017"
  command: mongod --smallfiles