static:
  build: static
  command: bundle exec middleman server --force-polling --verbose --latency=2 --port=80
  links: 
    - api
  ports:
    - "3002:80"
  volumes:
    - ${PWD}/static/middleman:/home/app
    - ${PWD}/static/config/config.js.coffee:/home/app/source/js/app/config/config.js.coffee
 
test:
  build: test
  command: guard -p
  links: 
    - mongo
  volumes:
    - ${PWD}/test/Gemfile:/home/app/Gemfile
    - ${PWD}/test/Gemfile.lock:/home/app/Gemfile.lock
    - ${PWD}/test/Guardfile:/home/app/Guardfile
    - ${PWD}/static/middleman/source:/home/app/source
    - ${PWD}/api:/home/app/api
    - ${PWD}/test/static/config/mongoid.yml:/home/app/config/mongoid.yml
    - ${PWD}/test/static/config/config.js.coffee:/home/app/source/js/app/config/config.js.coffee
    - ${PWD}/test/static/features:/home/app/features
    - ${PWD}/test/static/lib:/home/app/lib
    - ${PWD}/test/static/config.rb:/home/app/config.rb
    - ${PWD}/test/.rspec:/home/app/.rspec
    - ${PWD}/test/coverage:/home/app/coverage
    - ${PWD}/test/screenshots:/home/app/screenshots
  ports:
    - "4567:4567"


api:
  build: api
  command: rackup -p 80
  links:
    - mongo
  ports:
    - "3000:80"
  volumes:
    - ${PWD}/api:/home/app

cms:
  build: cms
  command:  bundle exec rackup -p 80 -o 0.0.0.0
  environment:
    - SECRET_KEY_BASE=as2387sd2370sd210128sd8023
  ports:
    - "3001:80"
  links:
    - mongo
  volumes:
    - ${PWD}/cms:/home/app

mongo:
  image: mongo
  ports:
    - "27017:27017"
  command: mongod --smallfiles