---
services:
  api:
    git: git@codebasehq.com:steam/amsterdam_rb/api.git
    git_branch: develop
    command: nginx
    traffic_matches:
    - api_amsterdamrb.steamlab.nl
    ports:
    - 80:80:443
  cms:
    git: git@codebasehq.com:steam/amsterdam_rb/cms.git
    git_branch: develop
    command: nginx
    traffic_matches:
    - cms_amsterdamrb.steamlab.nl
    ports:
    - 80:80:443
  static:
    git: git@codebasehq.com:steam/amsterdam_rb/static.git
    git_branch: develop
    command: nginx
    traffic_matches:
    - amsterdamrb.steamlab.nl
    ports:
    - 80:80:443
databases:
- mongodb
